# This file created by conda-build 3.17.7
# meta.yaml template originally from:
# C:\ci\containers\000001skdr6\tmp\build\80754af9\rsync-recipes\bokeh-1.0.4-python_3.7-on-winbuilder, last modified Thu Jan 17 14:25:36 2019
# ------------------------------------------------

package:
    name: bokeh
    version: 1.0.4
source:
    sha256: ceeb6a75afc1b2de00c2b8b6da121dec3fb77031326897b80d4375a70e96aebf
    url: https://pypi.io/packages/source/b/bokeh/bokeh-1.0.4.tar.gz
build:
    entry_points:
        - bokeh = bokeh.__main__:main
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.11.29 py37_0
        - openssl 1.1.1a he774522_0
        - pip 18.1 py37_0
        - python 3.7.2 h8c8aaf0_0
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.3 py37_0
        - wincertstore 0.2 py37_0
    run:
        - jinja2 >=2.7
        - numpy >=1.7.1
        - packaging >=16.8
        - pillow >=4.0
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.1
        - pyyaml >=3.10
        - six >=1.5.2
        - tornado >=4.3
test:
    commands:
        - bokeh --help
    imports:
        - bokeh
        - bokeh.application
        - bokeh.application.handlers
        - bokeh.client
        - bokeh.command
        - bokeh.command.subcommands
        - bokeh.core
        - bokeh.core.property
        - bokeh.core.validation
        - bokeh.models
        - bokeh.models.widgets
        - bokeh.plotting
        - bokeh.protocol
        - bokeh.protocol.messages
        - bokeh.sampledata
        - bokeh.server
        - bokeh.server.views
        - bokeh.sphinxext
        - bokeh.themes
        - bokeh.util
about:
    description: 'Bokeh is a Python interactive visualization library that targets

        modern web browsers for presentation. Its goal is to provide elegant,

        concise  construction of novel graphics in the style of D3.js, and to

        extend this capability with high-performance interactivity over very

        large or streaming datasets. Bokeh can help anyone who would like to

        quickly and easily create interactive plots, dashboards, and data

        applications.

        '
    dev_url: http://github.com/bokeh/bokeh
    doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
    home: http://bokeh.pydata.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Statistical and novel interactive HTML plots for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - almarklein
        - jakirkham
        - ocefpaf
