# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# C:\ci\containers\0000179qe52\tmp\build\80754af9\rsync-recipes\icu-58.2-cxx_compilervs2015c_compilervs2015-on-winbuilder, last modified Thu Nov 16 13:53:41 2017
# ------------------------------------------------

package:
    name: icu
    version: '58.2'
source:
    fn: icu4c-58_2-src.tgz
    patches:
        - icu-config.patch
        - icu4c-4_9_1-mingw-w64-mkdir-compatibility.patch
    sha256: 2b0a4410153a9b20de0e20c7d8b66049a72aef244b53683d0d7521371683da0c
    url: http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-src.tgz
build:
    number: '1'
    run_exports:
        - icu >=58.2,<59.0a0
    string: ha66f8fd_1
requirements:
    build:
        - m2-base 1.0.0 2
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-dash 0.5.8 2
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gettext 0.19.7 4
        - m2-gmp 6.1.0 3
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-liblzma 5.2.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-make 4.1 5
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-sed 4.2.2 3
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-util-linux 2.26.2 2
        - m2-which 2.21 3
        - m2-zlib 1.2.8 4
        - msys2-conda-epoch 20160418 1
        - vc 14 h2379b0c_2
        - vs2015_runtime 14.0.25123 hd4c4e62_2
        - vs2015_win-64 14.0.25123 hf5d5b87_2
    run:
        - vc 14.*
test:
    commands:
        - genbrk --help
        - gencfu --help
        - gencnval --help
        - gendict --help
        - icuinfo --help
        - makeconv gb-18030-2000.ucm
    files:
        - de.txt
        - gb-18030-2000.ucm
about:
    description: 'ICU is a mature, widely used set of C/C++ and Java libraries providing

        Unicode and Globalization support for software applications. ICU is

        widely portable and gives applications the same results on all platforms

        and between C/C++ and Java software.

        '
    dev_url: http://source.icu-project.org/repos/icu/
    doc_url: http://site.icu-project.org/design
    home: http://site.icu-project.org/
    license: MIT
    summary: International Components for Unicode.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - msarahan
        - ocefpaf
